=== pontsoleil/Japan_core/data/xml/ADC/AdcGlDetails.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- XML Definition of message hierarchy                                              -->
<!-- Message:             ADC GL Details v1.0                                         -->
<!-- Message Rev.:        8                                                           -->
<!-- Transaction:         AA - Audit Data Collection                                  -->
<!-- Transaction Rev.:    271                                                         -->
<!-- Datamodel:           Audit Data Collection Datamodel, version HEAD               -->
<!-- Datamodel Rev.:      347                                                         -->
<!-- Definition type:     W3C Schema (http://www.w3.org/XML/Schema)                   -->
<!-- XML tagset used:     AdcsML                                                      -->
<!-- Generated at:        02-05-2021 15:53:54                                         -->
<!-- Generated using:     EC-Design 2.5.0 (http://www.ec-design.nl)                   -->
<!-- Generated by:        Jan Vrijenhoek (Digitect)                                   -->
<!-- Organisation:        Digitect B.V. (Digitect)                                    -->
<!-- NOTE:    This schema was generated automatically: manual modifications will be lost -->
<!-- NOTE:    Additional rules/conditions regarding the definition may exist, see functional hierarchical specification -->
<xsd:schema 
		targetNamespace="http://schemas.iso.org/AdcsML/Messages/AdcGlDetails-v1"
		elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0"
		xmlns:str="http://schemas.iso.org/AdcsML/Messages/AdcGlDetails-v1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="AdcGlDetails">
		<xsd:annotation>
			<xsd:documentation>MESSAGE</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="GlDtls" minOccurs="0" maxOccurs="unbounded">
					<xsd:annotation>
						<xsd:documentation>GL DETAILS</xsd:documentation>
					</xsd:annotation>
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="JrnId" minOccurs="1" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Journal ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="JrnNr" minOccurs="0" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Journal Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="GlAcntNr" minOccurs="0" maxOccurs="1" type="str:TypGlAcntNr100">
								<xsd:annotation>
									<xsd:documentation>GL Account Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="FiscYr" minOccurs="0" maxOccurs="1" type="str:TypYrId">
								<xsd:annotation>
									<xsd:documentation>Fiscal Year</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntingPer" minOccurs="0" maxOccurs="1" type="str:TypPerId">
								<xsd:annotation>
									<xsd:documentation>Accounting Period</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="EffectiveDt" minOccurs="0" maxOccurs="1" type="str:TypDt">
								<xsd:annotation>
									<xsd:documentation>Effective Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="JrnLnNr" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Journal Line Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="JeTypCd" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>JE Type Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="JeHdrDscr" minOccurs="0" maxOccurs="1" type="str:TypText1000">
								<xsd:annotation>
									<xsd:documentation>JE Header Description</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="JeLnDscr" minOccurs="0" maxOccurs="1" type="str:TypText1000">
								<xsd:annotation>
									<xsd:documentation>JE Line Description</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SrcCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
								<xsd:annotation>
									<xsd:documentation>Source Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BillNr" minOccurs="0" maxOccurs="1" type="str:TypText100">
								<xsd:annotation>
									<xsd:documentation>Bill Number</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BillTypCd" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Bill Type Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="BillDt" minOccurs="0" maxOccurs="1" type="str:TypDt">
								<xsd:annotation>
									<xsd:documentation>Bill Date</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="Qt" minOccurs="0" maxOccurs="1" type="str:TypQt">
								<xsd:annotation>
									<xsd:documentation>Quantity</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="UomCd" minOccurs="0" maxOccurs="1" type="str:TypMeaUnitCd">
								<xsd:annotation>
									<xsd:documentation>UOM Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="UnitPrice" minOccurs="0" maxOccurs="1" type="str:TypAmt8">
								<xsd:annotation>
									<xsd:documentation>Unit Price</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="SetlMthdCd" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Settlement Method Code</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CrDbInd" minOccurs="0" maxOccurs="1" type="str:TypCrDbCd">
								<xsd:annotation>
									<xsd:documentation>Credit Debit Indicator</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RevInd" minOccurs="0" maxOccurs="1" type="str:TypRevIndCd">
								<xsd:annotation>
									<xsd:documentation>Reversal Indicator</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="RevJrnId" minOccurs="0" maxOccurs="1" type="str:TypId100">
								<xsd:annotation>
									<xsd:documentation>Reversal Journal ID</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="CnclSign" minOccurs="0" maxOccurs="1" type="str:TypBoolean">
								<xsd:annotation>
									<xsd:documentation>Cancellation Sign</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntSgEmp" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Account Segment Employee</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntSgProj" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Account Segment Project</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="AcntSgBankAcnt" minOccurs="0" maxOccurs="1" type="str:TypId60">
								<xsd:annotation>
									<xsd:documentation>Account Segment Bank Account</xsd:documentation>
								</xsd:annotation>
							</xsd:element>
							<xsd:element name="TrAmt" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>gl details - TRANSACTION AMOUNT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="FuncAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Functional Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="FuncCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Functional Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Transaction Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="TrCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Transaction Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Reporting Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="RprtCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Reporting Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocAmt" minOccurs="0" maxOccurs="1" type="str:TypAmt">
											<xsd:annotation>
												<xsd:documentation>Local Amount</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="LocCurCd" minOccurs="0" maxOccurs="1" type="str:TypCurCd">
											<xsd:annotation>
												<xsd:documentation>Local Currency Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Crea" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>gl details - CREATED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Tm" minOccurs="0" maxOccurs="1" type="str:TypTm">
											<xsd:annotation>
												<xsd:documentation>Time</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Aprv" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>gl details - APPROVED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="Dt" minOccurs="0" maxOccurs="1" type="str:TypDt">
											<xsd:annotation>
												<xsd:documentation>Date</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="Posted" minOccurs="0" maxOccurs="1">
								<xsd:annotation>
									<xsd:documentation>gl details - POSTED</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="UserId" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>User ID</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="AcntSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>gl details - ACCOUNT SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="AcntSgNr" minOccurs="0" maxOccurs="1" type="str:TypText60">
											<xsd:annotation>
												<xsd:documentation>Account Segment Number</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
										<xsd:element name="AcntSgCd" minOccurs="0" maxOccurs="1" type="str:TypText60">
											<xsd:annotation>
												<xsd:documentation>Account Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="BusSg" minOccurs="0" maxOccurs="unbounded">
								<xsd:annotation>
									<xsd:documentation>gl details - BUSINESS SEGMENT</xsd:documentation>
								</xsd:annotation>
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="BusSgCd" minOccurs="0" maxOccurs="1" type="str:TypId25">
											<xsd:annotation>
												<xsd:documentation>Business Segment Code</xsd:documentation>
											</xsd:annotation>
										</xsd:element>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	<!-- AMOUNT: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypAmt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- AMOUNT8: FORMAT: N..22,8 -->
	<xsd:simpleType name="TypAmt8">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="8"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- BOOLEAN: FORMAT: N1 -->
	<xsd:simpleType name="TypBoolean">
		<xsd:restriction base="xsd:boolean"/>
	</xsd:simpleType>
	<!-- CREDIT DEBIT CODE: FORMAT: AN..1 -->
	<xsd:simpleType name="TypCrDbCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
			<xsd:enumeration value="C">
				<xsd:annotation>
					<xsd:documentation>credit</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
			<xsd:enumeration value="D">
				<xsd:annotation>
					<xsd:documentation>debit</xsd:documentation>
				</xsd:annotation>
			</xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- CURRENCY CODE: FORMAT: AN3 -->
	<xsd:simpleType name="TypCurCd">
		<xsd:annotation>
			<xsd:documentation>ISO 4217, codes for representation of currencies.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="xsd:string">
			<xsd:length value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- DATE: FORMAT: AN10 -->
	<xsd:simpleType name="TypDt">
		<xsd:restriction base="xsd:date"/>
	</xsd:simpleType>
	<!-- GL ACCOUNT NUMBER 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypGlAcntNr100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypId100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 25: FORMAT: AN..25 -->
	<xsd:simpleType name="TypId25">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="25"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- IDENTIFIER 60: FORMAT: AN..60 -->
	<xsd:simpleType name="TypId60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- MEASUREMENT UNIT CODE: FORMAT: AN..80 -->
	<xsd:simpleType name="TypMeaUnitCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="80"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- PERIOD IDENTIFIER: FORMAT: AN..15 -->
	<xsd:simpleType name="TypPerId">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="15"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- QUANTITY: FORMAT: N..22,4 -->
	<xsd:simpleType name="TypQt">
		<xsd:restriction base="xsd:decimal">
			<xsd:totalDigits value="22"/>
			<xsd:fractionDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- REVERSAL INDICATOR CODE: FORMAT: AN..1 -->
	<xsd:simpleType name="TypRevIndCd">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 100: FORMAT: AN..100 -->
	<xsd:simpleType name="TypText100">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="100"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 1000: FORMAT: AN..1000 -->
	<xsd:simpleType name="TypText1000">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1000"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TEXT 60: FORMAT: AN..60 -->
	<xsd:simpleType name="TypText60">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="60"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- TIME: FORMAT: AN..8 -->
	<xsd:simpleType name="TypTm">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="8"/>
		</xsd:restriction>
	</xsd:simpleType>
	<!-- YEAR IDENTIFIER: FORMAT: N..4 -->
	<xsd:simpleType name="TypYrId">
		<xsd:restriction base="xsd:nonNegativeInteger">
			<xsd:totalDigits value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== pontsoleil/Japan_core/data/xml/ADC/pca.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<AdcGlDetails xmlns="http://schemas.iso.org/AdcsML/Messages/AdcGlDetails-v1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://schemas.iso.org/AdcsML/Messages/AdcGlDetails-v1 AdcGlDetails.xsd">
    <GlDtls>
        <JrnId>0001-20090401-18-1-1-463</JrnId>
        <GlAcntNr>726</GlAcntNr>
        <EffectiveDt>2009-04-01</EffectiveDt>
        <JeLnDscr>旅費</JeLnDscr>
        <SrcCd>PCA会計９V.2-仕訳ﾃﾞｰﾀの受入</SrcCd>
        <CrDbInd>D</CrDbInd>
        <TrAmt>
            <FuncAmt>18572</FuncAmt>
            <FuncCurCd>JPY</FuncCurCd>
        </TrAmt>
        <Crea>
            <UserId>pca</UserId>
            <Dt>2009-04-19</Dt>
        </Crea>
    </GlDtls>
    <GlDtls>
        <JrnId>0001-20090401-18-1-2-463</JrnId>
        <GlAcntNr>191</GlAcntNr>
        <EffectiveDt>2009-04-01</EffectiveDt>
        <SrcCd>PCA会計９V.2-仕訳ﾃﾞｰﾀの受入</SrcCd>
        <CrDbInd>D</CrDbInd>
        <TrAmt>
            <FuncAmt>928</FuncAmt>
            <FuncCurCd>JPY</FuncCurCd>
        </TrAmt>
        <Crea>
            <UserId>pca</UserId>
            <Dt>2009-04-19</Dt>
        </Crea>
    </GlDtls>
    <GlDtls>
        <JrnId>0001-20090401-18-1-3-463</JrnId>
        <GlAcntNr>111</GlAcntNr>
        <EffectiveDt>2009-04-01</EffectiveDt>
        <JeLnDscr>旅費</JeLnDscr>
        <SrcCd>PCA会計９V.2-仕訳ﾃﾞｰﾀの受入</SrcCd>
        <CrDbInd>C</CrDbInd>
        <TrAmt>
            <FuncAmt>19500</FuncAmt>
            <FuncCurCd>JPY</FuncCurCd>
        </TrAmt>
        <Crea>
            <UserId>pca</UserId>
            <Dt>2009-04-19</Dt>
        </Crea>
    </GlDtls>
    <GlDtls>
        <JrnId>0001-20090401-246-2-1-465</JrnId>
        <GlAcntNr>726</GlAcntNr>
        <EffectiveDt>2009-04-01</EffectiveDt>
        <JeLnDscr>旅費</JeLnDscr>
        <SrcCd>PCA会計９V.2-仕訳ﾃﾞｰﾀの受入</SrcCd>
        <CrDbInd>D</CrDbInd>
        <TrAmt>
            <FuncAmt>9524</FuncAmt>
            <FuncCurCd>JPY</FuncCurCd>
        </TrAmt>
        <Crea>
            <UserId>pca</UserId>
            <Dt>2009-04-19</Dt>
        </Crea>
    </GlDtls>
    <GlDtls>
        <JrnId>0001-20090401-246-2-2-465</JrnId>
        <GlAcntNr>191</GlAcntNr>
        <EffectiveDt>2009-04-01</EffectiveDt>
        <SrcCd>PCA会計９V.2-仕訳ﾃﾞｰﾀの受入</SrcCd>
        <CrDbInd>D</CrDbInd>
        <TrAmt>
            <FuncAmt>476</FuncAmt>
            <FuncCurCd>JPY</FuncCurCd>
        </TrAmt>
        <Crea>
            <UserId>pca</UserId>
            <Dt>2009-04-19</Dt>
        </Crea>
    </GlDtls>
    <GlDtls>
        <JrnId>0001-20090401-246-2-3-465</JrnId>
        <GlAcntNr>111</GlAcntNr>
        <EffectiveDt>2009-04-01</EffectiveDt>
        <JeLnDscr>旅費</JeLnDscr>
        <SrcCd>PCA会計９V.2-仕訳ﾃﾞｰﾀの受入</SrcCd>
        <CrDbInd>C</CrDbInd>
        <TrAmt>
            <FuncAmt>10000</FuncAmt>
            <FuncCurCd>JPY</FuncCurCd>
        </TrAmt>
        <Crea>
            <UserId>pca</UserId>
            <Dt>2009-04-19</Dt>
        </Crea>
    </GlDtls>
</AdcGlDetails>
